function(display_vars)
    message(STATUS "---------------------------------")
    message(STATUS "CMAKE_SOURCE_DIR ${CMAKE_SOURCE_DIR}")
    message(STATUS "PROJECT_SOURCE_DIR ${PROJECT_SOURCE_DIR}")
    message(STATUS "CMAKE_CURRENT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}")
    message(STATUS "CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_DIR}")
    message(STATUS "CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}")
    message(STATUS "CMAKE_BINARY_DIR ${CMAKE_BINARY_DIR}")
    message(STATUS "---------------------------------")
endfunction(display_vars)
